website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

# user (one-to-many) projects
# user (one-to-many) Bug
# project (one-to-many) Bug

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    projects = db.relationship('Project', backref='user')
    bugs = db.relationship('Bug', backref='user')


 
class Bug(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    description = db.Column(db.String(500))
    status = db.Column(db.String(50))
    date_reported = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    project_id = db.Column(db.Integer, db.ForeignKey('project.id'))

class Project(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150)) 
    description = db.Column(db.String(500))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    bugs = db.relationship('Bug', backref='project')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, current_user
from datetime import datetime, timedelta
from .utils import time_ago


db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.jinja_env.filters['time_ago'] = time_ago

    from .models import User, Project
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @app.context_processor
    def inject_projects():
        if current_user.is_authenticated:
            projects = Project.query.all()
        else:
            projects = []
        return dict(projects=projects)


    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    


    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.dashboard'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from .models import User, Project, Bug
from . import db
import json

views = Blueprint('views', __name__)\


@views.route('/')
@login_required
def dashboard():
    issues = Bug.query.all()

    users = User.query.all()

    projects = current_user.projects

    return render_template("dashboard.html", user=current_user, issues=issues, users=users, project=projects)

@views.route('/tickets/<int:project_id>')
@login_required
def project_tickets(project_id):
    # Get the project from the database based on the project_id
    project = Project.query.get(project_id)

    if not project:
        abort(404)

    # Get the tickets associated with the project
    tickets = Bug.query.filter_by(project_id=project.id).all()

    # Filter tickets for each status
    open_tickets = [ticket for ticket in tickets if ticket.status == 'Open']
    in_progress_tickets = [ticket for ticket in tickets if ticket.status == 'In Progress']
    closed_tickets = [ticket for ticket in tickets if ticket.status == 'Closed']

    return render_template('project_tickets.html', user=current_user, project=project,
                            tickets=tickets, open_tickets=open_tickets, 
                            in_progress_tickets=in_progress_tickets, closed_tickets=closed_tickets)

@views.route('/create_issue', methods=['GET', 'POST'])
@login_required
def create_issue():
    if request.method == 'POST':
        # Get the form data submitted by the user
        issue_name = request.form['issueName']
        description = request.form['description']
        status = request.form['status']
        assignee_id = int(request.form['assignee'])
        project_id = int(request.form['project'])

        user = current_user  # Current logged-in user (creator of the issue)
        assignee = User.query.get(assignee_id)
        project = Project.query.get(project_id)


        new_issue = Bug(title=issue_name, description=description, status=status, user=user, project=project)
        new_issue.assignee = assignee  # Set the assignee for the new issue


        db.session.add(new_issue)
        db.session.commit()

        return redirect(url_for('views.dashboard'))

    else:
        #  GET request
        #  pass the necessary data (users and projects) to populate the dropdowns
        users = User.query.all()  
        projects = Project.query.all() 
        issues = Bug.query.all()
        return render_template("create_issue.html", user=current_user, users=users, projects=projects, issue=issues)



@views.route('/update_issue/<int:issue_id>', methods=['GET', 'POST'])
@login_required
def update_issue(issue_id):
    issue = Bug.query.get_or_404(issue_id)

    if request.method == 'POST':
        issue.title = request.form['title']
        issue.description = request.form['description']
        issue.status = request.form['status']

        db.session.commit()

        return redirect(url_for('views.dashboard'))


@views.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():
    if request.method == 'POST':
        project_name = request.form['projectName']
        description = request.form['description']

        new_project = Project(name=project_name, description=description, user=current_user)

        db.session.add(new_project)
        db.session.commit()

        return redirect(url_for('views.create_issue'))

    else:
        return render_template("create_project.html", user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <style>
  
    #sidebar {
      position: fixed;
      top: 0;
      left: 0;
      height: 100%;
      padding-top: 15px; 
      background-color: #001E2C; 
      color: white !important; 
    }
    #sidebar h3 {
      padding-left: 15px; 
      padding-top: 10px; 
      padding-bottom: 10px;
    }
    #sidebar a {
      color: white !important;
    }
    #sidebar .dropdown-menu a {
      color: black !important;
    }
  </style>
  
  
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <!-- Sidebar -->
      <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block sidebar "style="background-color:#001E2C;">
        <div class="position-sticky">
          <div class="sidebar-header">
            <h3>Bug Tracker</h3>
          </div>
          <ul class="nav flex-column">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/">
                <i class="fa fa-bug"></i> 
                &nbsp;Bugs
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="projectDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-folder"></i>
                &nbsp;Projects
              </a>
              </a>
              <div class="dropdown-menu" aria-labelledby="projectDropdown">
                {% if user and user.is_authenticated %}
                {% for project in projects %}
                <a class="dropdown-item" href="{{ url_for('views.project_tickets', project_id=project.id) }}">{{ project.name }}</a>
                {% endfor %}
                {% else %}
                <a class="dropdown-item disabled" href="#">No Projects</a>
                {% endif %}
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create_project">
                <i class="fa fa-plus"></i> 
                &nbsp;New Project
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create_issue">
                <i class="fa fa-plus-square"></i>
                &nbsp;New Issue
              </a>
            </li>
            <div class="mt-auto">
            <li class="nav-item">
              <a class="nav-link" href="/logout">
                <i class="fa fa-sign-out"></i> 
                &nbsp;Logout
              </a>
            </li>
          </div>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">  
                <i class="fa fa-sign-in"></i> 
                &nbsp;Login
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/sign-up">
                <i class="fa fa-user-plus"></i> 
                &nbsp;Sign Up
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <!-- Page Content -->
      <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

        <div class="container">
          {% block content %} {% endblock %}
        </div>
      </main>
    </div>
  </div>

  <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  {% block javascript %}{% endblock %}
</body>
</html>

website/templates/create_issue.html
{% extends "base.html" %}

{% block title %}Create Issue{% endblock %}

{% block content %}
  <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="col-md-10"> 
      <div class="card shadow-sm">
        <div class="card-body">
          <h1 class="card-title text-center mb-4">Create Issue</h1>

          <form method="POST">
            <div class="form-group row">
              <label for="issueName" class="col-sm-2 col-form-label">Issue Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="issueName" name="issueName" placeholder="Enter issue name" required>
              </div>
            </div>

            <div class="form-group row">
              <label for="description" class="col-sm-2 col-form-label">Description</label>
              <div class="col-sm-10">
                <textarea class="form-control" id="description" name="description" rows="4" placeholder="Enter issue description" required></textarea>
              </div>
            </div>

            <div class="form-group row">
              <label for="status" class="col-sm-2 col-form-label">Status</label>
              <div class="col-sm-10">
                <select class="form-control" id="status" name="status" required>
                  <option value="Open">Open</option>
                  <option value="In Progress">In Progress</option>
                  <option value="Closed">Closed</option>
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label for="assignee" class="col-sm-2 col-form-label">Assignee</label>
              <div class="col-sm-10">
                <select class="form-control" id="assignee" name="assignee" required>
                  {% for user in users %}
                  <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label for="project" class="col-sm-2 col-form-label">Project</label>
              <div class="col-sm-10">
                <select class="form-control" id="project" name="project" required>
                  {% for project in projects %}
                  <option value="{{ project.id }}">{{ project.name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>

            <div class="form-group row">
              <div class="col-sm-10 offset-sm-2">
                <button type="submit" class="btn btn-primary btn-block">Create Issue</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/create_project.html
{% extends "base.html" %}

{% block title %}Create Project{% endblock %}

{% block content %}
  <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-body">
          <h1 class="card-title text-center mb-4">Create Project</h1>

          <form method="POST">
            <div class="form-group">
              <label for="projectName">Project Name</label>
              <input type="text" class="form-control" id="projectName" name="projectName" placeholder="Enter project name" required>
            </div>

            <div class="form-group">
              <label for="description">Description</label>
              <textarea class="form-control" id="description" name="description" rows="4" placeholder="Enter project description" required></textarea>
            </div>

            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-primary btn-block">Create Project</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Bug{% endblock %}

{% block content %}
<div class="container mt-4">
  <h2 class="pl-2">My Bugs</h2>
</div>
<div class="container mt-4">

  <!-- Row divided into two columns -->
  <div class="row">
    <div class="col-md-12">
      <div class="table-responsive">
        <table class="table table-hover table">
          <thead>
            <tr>
              <th>Bug</th>
              <th>Status</th>
              <th>Date Created</th>
              <th>Project</th>
            </tr>
          </thead>
          <tbody>
            {% for issue in user.bugs %}
            <tr class="clickable-row" data-toggle="modal" data-target="#updateIssueModal{{ issue.id }}">
              <td>{{ issue.title }}</td>
              <td>
                <span class="badge rounded-pill d-inline {% if issue.status == 'Open' %}badge-primary{% elif issue.status == 'In Progress' %}badge-warning{% elif issue.status == 'Closed' %}badge-success{% endif %}">
                  {{ issue.status }}
                </span>
              </td>
              <td>{{ issue.date_reported|time_ago }}</td>
              <td>{{ issue.project.name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


{% for issue in user.bugs %}
<div class="modal fade" id="updateIssueModal{{ issue.id }}" tabindex="-1" role="dialog" aria-labelledby="updateIssueModalLabel{{ issue.id }}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updateIssueModalLabel">Update Issue - {{ issue.title }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ url_for('views.update_issue', issue_id=issue.id) }}">
          <!-- Add form fields for updating issue details (e.g., title, description, status) -->
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ issue.title }}">
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description">{{ issue.description }}</textarea>
          </div>
          <div class="form-group">
            <label for="status">Status</label>
            <select class="form-control" id="status" name="status">
              <option value="Open" {% if issue.status == 'Open' %}selected{% endif %}>Open</option>
              <option value="In Progress" {% if issue.status == 'In Progress' %}selected{% endif %}>In Progress</option>
              <option value="Closed" {% if issue.status == 'Closed' %}selected{% endif %}>Closed</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Update Issue</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<script>
document.addEventListener("DOMContentLoaded", function () {
  var rows = document.querySelectorAll(".clickable-row");
  rows.forEach(function (row) {
    row.addEventListener("click", function () {
      var targetModalId = row.dataset.target;
      if (targetModalId) {
        var modal = document.querySelector(targetModalId);
        if (modal) {
          $(modal).modal("show");
        }
      }
    });
  });
});

</script>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/project_tickets.html
<!DOCTYPE html>
<html>
<head>
  <style>
 .card-header .text-muted {
  color: white !important;
    }
    .card-header h5 {
      color: white !important;
    }
    .jumbotron {
      background-color: transparent !important;
    }
    .jumbotron .well {
      background-color: transparent !important; 
    }
  </style>

</head>
{% extends "base.html" %}
{% block title %}{{ project.name }} Tickets{% endblock %}

{% block content %}
<div class="jumbotron p-2">
  <div class="well text-center">
    <h2>Project {{project.name}}</h2>
  </div>
</div>
{% if tickets %}
  <div class="container">
    <div class="row">
      <div class="col">
        <!-- Open Tickets -->
        <div class="card text-black bg-primary mb-3">
          <div class="card-header">
            <h5 class="card-title">Open</h5>
            <small class="text-muted">{{ open_tickets|length }} tickets available</small>
          </div>
          <ul class="list-group list-group-flush">
            {% for ticket in tickets if ticket.status == "Open" %}
            <li class="list-group-item">
              <strong> {{ ticket.title }}</strong>
              <br>
              <small class="text-muted">Created by: {{ ticket.user.first_name}},  {{ ticket.date_reported | time_ago }}</small>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col">
        <!-- In Progress Tickets -->
        <div class="card text-black bg-warning mb-3">
          <div class="card-header">
            <h5 class="card-title">In Progress</h5>
            <small class="text-muted">{{ in_progress_tickets|length }} tickets available</small>
          </div>
          <ul class="list-group list-group-flush">
            {% for ticket in tickets if ticket.status == "In Progress" %}
            <li class="list-group-item">
              <strong> {{ ticket.title }}</strong>
              <br>
              <small class="text-muted">Created by: {{ ticket.user.first_name}},  {{ ticket.date_reported | time_ago }}</small>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col">
        <!-- Closed Tickets -->
        <div class="card text-black bg-success mb-3">
          <div class="card-header">
            <h5 class="card-title">Closed</h5>
            <small class="text-muted">{{ closed_tickets|length }} tickets available</small>
          </div>
          <ul class="list-group list-group-flush">
            {% for ticket in tickets if ticket.status == "Closed" %}
            <li class="list-group-item">
              <strong> {{ ticket.title }}</strong>
              <br>
              <small class="text-muted">Created by: {{ ticket.user.first_name}},  {{ ticket.date_reported | time_ago }}</small>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
{% else %}
  <p>No tickets found for this project.</p>
{% endif %}
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}